[package]
name = "crgc_derive"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/zarmot/crgc"
description = "Rust single thread GC based on reference counting + cycle removal. Inspired by QuickJS."
